apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "whatsapp-reminder.fullname" . }}-config
  labels:
    {{- include "whatsapp-reminder.labels" . | nindent 4 }}
data:
  config.yaml: |
    googleSheets:
      spreadsheetId: {{ .Values.config.googleSheets.spreadsheetId | quote }}
      sheetName: {{ .Values.config.googleSheets.sheetName | quote }}
      serviceAccountFile: {{ .Values.config.googleSheets.serviceAccountFile | quote }}
    email:
      host: {{ .Values.config.email.host | quote }}
      port: {{ .Values.config.email.port }}
      from: {{ .Values.config.email.from | quote }}
      to:
        {{- range .Values.config.email.to }}
        - {{ . | quote }}
        {{- end }}
      startTLS: {{ .Values.config.email.startTLS }}
      timeout: {{ .Values.config.email.timeout | quote }}
      auth:
        required: {{ .Values.config.email.auth.required }}
        username: {{ .Values.config.email.auth.username | quote }}
        password: {{ .Values.config.email.auth.password | quote }}
    app:
      timeLocation: {{ .Values.config.app.timeLocation | quote }}
      retentionTime: {{ .Values.config.app.retentionTime | quote }}
      logLevel: {{ .Values.config.app.logLevel | quote }}
